node {

    def mvnHome = tool 'apache-maven-3.3.3'
    def jdk = tool 'jdk8_40'
    def buildEnvironment = ["JAVA_HOME=${jdk}", "PATH+MAVEN=${mvnHome}/bin:${env.JAVA_HOME}/bin"]

    try {

        stage('clean') {
            deleteDir()
        }

        stage('scm') {
            checkout scm			
        }

        stage('build') {
            dir('spark-importer')
			{
				withEnv(buildEnvironment) {
					sh 'mvn clean package -Dbuild.number=${BUILD_NUMBER}'
				}
			}
        }

       
    } catch (error) {

        currentBuild.result = "FAILURE"

        mail body: "Zum Build-Protokoll des bpmn.ai spark-importer https://portal.intern.viadee.de/jenkins/job/bpmn.ai%20spark%20importer/workflow-stage/" ,
            replyTo: '',
            subject: 'bpmn.ai Build fehlgeschlagen',
            to: 'mim@viadee.de'
			cc: 'kof@viadee.de'

        throw err

    }
}
